name: Android Quality & Reviewers

on:
  pull_request:
    # 'synchronize' ensures the check runs again whenever new commits are pushed to the PR
    types: [opened, ready_for_review, synchronize]

jobs:
  validation-and-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Run Detekt (Kotlin static code analysis)
      - name: Run Detekt
        run: ./gradlew detekt

      # Run Android Lint (Typically executed on the Debug build variant)
      - name: Run Android Lint
        run: ./gradlew lintDebug

      # This step will only execute if both Detekt and Lint pass successfully
      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: johnkenedyneves,LucasSimoesMartins
          re-request-when-approved: true
          re-request-when-changes-requested: true